CREATE TABLE `sign_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`token` varchar(64) NOT NULL,
	`customerName` varchar(256) NOT NULL,
	`customerEmail` varchar(320) NOT NULL,
	`customerPhone` varchar(64),
	`customerAddress` varchar(512),
	`estimateSnapshot` text NOT NULL,
	`collectionName` varchar(128),
	`colorName` varchar(128),
	`sqft` int NOT NULL DEFAULT 0,
	`grandTotal` decimal(10,2) NOT NULL,
	`finalTotal` decimal(10,2) NOT NULL,
	`pricePerSqft` decimal(10,2) NOT NULL DEFAULT '0.00',
	`laborName` varchar(128),
	`deliveryName` varchar(128),
	`contractText` text NOT NULL,
	`scopeOfWork` text,
	`pricingBreakdown` text,
	`showPricing` int NOT NULL DEFAULT 1,
	`status` varchar(16) NOT NULL DEFAULT 'pending',
	`signedName` varchar(256),
	`signedAt` timestamp,
	`stripeDepositSessionId` varchar(256),
	`checkoutUrl` text,
	`orderId` int,
	`expiresAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sign_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `sign_requests_token_unique` UNIQUE(`token`)
);
